package pe.com.gamarra360.backend.enums;

public enum GaleriaEnum {
    GAMA_MODA_PLAZA,
    PLAZA_GAMARRA,
    GALERIA_KRISTALES,
    CENTRO_COMERCIAL_GAMARRA,
    GALERIA_SANTA_LUCIA,
    GALERIA_EL_DORADO,
    GALERIA_DAMERO,
    GALERIA_EL_REY,
    GALERIA_GENERACION_GAMARRA,
    GALERIA_GAMARRA_SAN_PEDRO,
    GALERIA_YA,
    LA_PORTADA_DE_GAMARRA,
    GALERIA_GUIZADO,
    GALERIA_AUGUSTO_ALLCCA
}
